"""Postgres/pgvector-backed `ReelStore`. One row per `SavedReel`."""

from __future__ import annotations

import logging
from collections.abc import Iterable
from datetime import timezone

import psycopg
from pgvector import Vector
from pgvector.psycopg import register_vector

from reel_vault.models import (
    UNCATEGORIZED,
    Correction,
    NeighbourPlacement,
    ProcessingStatus,
    SavedReel,
)
from reel_vault.search import keyword_score, merge_hits, metadata_text

logger = logging.getLogger(__name__)

# Long enough for a container still waking up, short enough that a database
# that isn't there gets said out loud rather than waited on forever.
DEFAULT_CONNECT_TIMEOUT = 10

# Separate from SCHEMA and run before it, because `register_vector` has to
# look the `vector` type up in the database and cannot find one that has not
# been created yet. Left inside SCHEMA, this ran one statement too late: on
# an existing vault it made no difference, and on a brand-new database it
# failed at startup with "vector type not found in the database" - the one
# case the README promises the app sets itself up in.
EXTENSION = "CREATE EXTENSION IF NOT EXISTS vector;"

SCHEMA = f"""
CREATE TABLE IF NOT EXISTS saved_reels (
    normalized_url TEXT PRIMARY KEY,
    caption TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{{}}',
    embedding VECTOR(384) NOT NULL,
    saved_at TIMESTAMPTZ NOT NULL
);

-- Added after the first release; ALTERs keep existing vaults working.
ALTER TABLE saved_reels
    ADD COLUMN IF NOT EXISTS collection TEXT NOT NULL DEFAULT '{UNCATEGORIZED}',
    ADD COLUMN IF NOT EXISTS subcollection TEXT,
    ADD COLUMN IF NOT EXISTS author_handle TEXT,
    ADD COLUMN IF NOT EXISTS author_name TEXT,
    ADD COLUMN IF NOT EXISTS thumbnail_ref TEXT,
    -- The curated half of the reel, kept as plain text so the keyword arm of
    -- search has something to match. Written by `reel_vault.search`
    -- rather than generated by Postgres: `array_to_string` over `tags` is not
    -- immutable, so a GENERATED column is rejected outright, and duplicating
    -- the definition in SQL would let it drift from the one the in-memory
    -- store uses.
    ADD COLUMN IF NOT EXISTS metadata_text TEXT NOT NULL DEFAULT '',
    -- The caption embedded on its own. The `embedding` column above also
    -- covers collection and tags, so it cannot answer "which reels read
    -- like this one?" without favouring whichever shelf shares the
    -- caption's vocabulary.
    ADD COLUMN IF NOT EXISTS caption_embedding VECTOR(384),
    ADD COLUMN IF NOT EXISTS user_placed BOOLEAN NOT NULL DEFAULT FALSE,
    -- What the video said and showed. The `_raw` halves are never embedded
    -- and never searched; they exist so a summary judged poor later can be
    -- remade from the words themselves, rather than by re-downloading a
    -- video whose source URL has since expired.
    ADD COLUMN IF NOT EXISTS transcript_raw TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS transcript_summary TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS frame_analysis_raw TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS frame_analysis_summary TEXT NOT NULL DEFAULT '',
    -- Deliberately defaulted to 'skipped', not 'pending': rows already in the
    -- vault when this column arrived predate the pipeline, and defaulting
    -- them to pending would queue every one of them for download the next
    -- time the bot starts. Backfilling them is a separate, deliberate job.
    -- The default flips to 'pending' immediately below, for rows written
    -- from here on.
    ADD COLUMN IF NOT EXISTS processing_status TEXT NOT NULL DEFAULT 'skipped';

ALTER TABLE saved_reels ALTER COLUMN processing_status SET DEFAULT 'pending';

CREATE INDEX IF NOT EXISTS saved_reels_pending_idx
    ON saved_reels (processing_status) WHERE processing_status = 'pending';

CREATE INDEX IF NOT EXISTS saved_reels_collection_idx
    ON saved_reels (collection, subcollection);
CREATE INDEX IF NOT EXISTS saved_reels_author_idx ON saved_reels (author_handle);
-- An expression index, so the tsvector is built once per row at write time
-- rather than for every row on every search.
CREATE INDEX IF NOT EXISTS saved_reels_metadata_idx
    ON saved_reels USING GIN (to_tsvector('english', metadata_text));

-- Every move the user has made, most recent first per reel, so one can be
-- taken back.
CREATE TABLE IF NOT EXISTS reel_corrections (
    id BIGSERIAL PRIMARY KEY,
    normalized_url TEXT NOT NULL,
    from_collection TEXT NOT NULL,
    from_subcollection TEXT,
    to_collection TEXT NOT NULL,
    to_subcollection TEXT,
    from_user_placed BOOLEAN NOT NULL DEFAULT FALSE,
    corrected_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS reel_corrections_url_idx
    ON reel_corrections (normalized_url, corrected_at DESC);
"""

COLUMNS = (
    "normalized_url, caption, tags, embedding, caption_embedding, collection, "
    "subcollection, author_handle, author_name, thumbnail_ref, user_placed, "
    "transcript_raw, transcript_summary, frame_analysis_raw, "
    "frame_analysis_summary, processing_status, saved_at"
)


class PostgresReelStore:
    def __init__(self, dsn: str, *, connect_timeout: int = DEFAULT_CONNECT_TIMEOUT) -> None:
        # Say where we are going before we try. An unreachable Postgres — the
        # container simply not started — TIMES OUT rather than refusing, so
        # without this the process hangs silently before the bot ever polls,
        # looking like a bot that starts fine and ignores every message.
        logger.info("Connecting to Postgres at %s", _describe(dsn))
        try:
            self._conn = psycopg.connect(
                dsn, autocommit=True, connect_timeout=connect_timeout
            )
        except psycopg.OperationalError as exc:
            raise RuntimeError(
                f"Could not reach Postgres at {_describe(dsn)} within "
                f"{connect_timeout}s. Is the database container running? "
                f"(psycopg: {exc})"
            ) from exc
        self._conn.execute(EXTENSION)
        register_vector(self._conn)
        self._conn.execute(SCHEMA)
        logger.info("Connected to Postgres; vault ready.")

    def find_by_url(self, normalized_url: str) -> SavedReel | None:
        row = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels WHERE normalized_url = %s",
            (normalized_url,),
        ).fetchone()
        return _to_reel(row) if row else None

    def save(self, reel: SavedReel) -> bool:
        cursor = self._conn.execute(
            f"INSERT INTO saved_reels ({COLUMNS}, metadata_text) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, "
            "%s, %s, %s, %s) "
            "ON CONFLICT (normalized_url) DO NOTHING",
            (
                reel.url,
                reel.caption,
                reel.tags,
                Vector(reel.embedding),
                Vector(reel.caption_embedding) if reel.caption_embedding else None,
                reel.collection,
                reel.subcollection,
                reel.author_handle,
                reel.author_name,
                reel.thumbnail_ref,
                reel.user_placed,
                reel.transcript_raw,
                reel.transcript_summary,
                reel.frame_analysis_raw,
                reel.frame_analysis_summary,
                reel.processing_status.value,
                reel.saved_at,
                metadata_text(reel.tags, reel.collection, reel.subcollection),
            ),
        )
        # DO NOTHING leaves rowcount at 0 when the URL was already there.
        return cursor.rowcount > 0

    def update(self, reel: SavedReel) -> None:
        """Overwrite an already-saved reel, keyed on its URL — every column
        except the key and the date it was first saved.

        Wholesale rather than a chosen subset, because the port says
        "overwrite" and the in-memory store used by every seam test does
        exactly that. A partial UPDATE agrees with it on the fields today's
        callers happen to change and diverges silently on the rest: a caller
        that edited a caption or a tag list would have been handed a reel
        back with the edit applied, the tests would have passed, and the
        column would never have moved. There is no seam test that can catch
        that, so the two implementations have to mean the same thing.

        The media columns travel with the embedding rather than in a setter
        of their own: a transcript written without re-embedding would be
        words the vault holds and no query can reach, and separating the two
        writes would make that an easy mistake to make twice.
        """
        self._conn.execute(
            "UPDATE saved_reels SET caption = %s, tags = %s, embedding = %s, "
            "caption_embedding = %s, collection = %s, subcollection = %s, "
            "author_handle = %s, author_name = %s, thumbnail_ref = %s, "
            "user_placed = %s, transcript_raw = %s, transcript_summary = %s, "
            "frame_analysis_raw = %s, frame_analysis_summary = %s, "
            "processing_status = %s, metadata_text = %s "
            "WHERE normalized_url = %s",
            (
                reel.caption,
                reel.tags,
                Vector(reel.embedding),
                Vector(reel.caption_embedding) if reel.caption_embedding else None,
                reel.collection,
                reel.subcollection,
                reel.author_handle,
                reel.author_name,
                reel.thumbnail_ref,
                reel.user_placed,
                reel.transcript_raw,
                reel.transcript_summary,
                reel.frame_analysis_raw,
                reel.frame_analysis_summary,
                reel.processing_status.value,
                metadata_text(reel.tags, reel.collection, reel.subcollection),
                reel.url,
            ),
        )

    def find_awaiting_media(self) -> list[SavedReel]:
        rows = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels "
            "WHERE processing_status = %s ORDER BY saved_at",
            (ProcessingStatus.PENDING.value,),
        ).fetchall()
        return [_to_reel(row) for row in rows]

    def find_similar_captions(
        self, caption_embedding: list[float], limit: int
    ) -> list[NeighbourPlacement]:
        vector = Vector(caption_embedding)
        rows = self._conn.execute(
            "SELECT caption, collection, subcollection, user_placed, "
            "1 - (caption_embedding <=> %s) AS similarity "
            "FROM saved_reels WHERE caption_embedding IS NOT NULL "
            "ORDER BY caption_embedding <=> %s LIMIT %s",
            (vector, vector, limit),
        ).fetchall()
        return [
            NeighbourPlacement(
                caption=caption,
                collection=collection,
                subcollection=subcollection,
                similarity=float(similarity),
                user_placed=user_placed,
            )
            for caption, collection, subcollection, user_placed, similarity in rows
        ]

    def record_correction(self, correction: Correction) -> None:
        self._conn.execute(
            "INSERT INTO reel_corrections (normalized_url, from_collection, "
            "from_subcollection, to_collection, to_subcollection, "
            "from_user_placed, corrected_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s)",
            (
                correction.url,
                correction.from_collection,
                correction.from_subcollection,
                correction.to_collection,
                correction.to_subcollection,
                correction.from_user_placed,
                correction.corrected_at,
            ),
        )

    def pop_last_correction(self, normalized_url: str) -> Correction | None:
        row = self._conn.execute(
            "DELETE FROM reel_corrections WHERE id = ("
            "  SELECT id FROM reel_corrections WHERE normalized_url = %s"
            "  ORDER BY corrected_at DESC, id DESC LIMIT 1"
            ") RETURNING normalized_url, from_collection, from_subcollection, "
            "to_collection, to_subcollection, from_user_placed, corrected_at",
            (normalized_url,),
        ).fetchone()
        if row is None:
            return None
        url, from_c, from_s, to_c, to_s, from_user, at = row
        return Correction(
            url=url,
            from_collection=from_c,
            from_subcollection=from_s,
            to_collection=to_c,
            to_subcollection=to_s,
            from_user_placed=from_user,
            corrected_at=at,
        )

    def known_collections(self) -> dict[str, list[str]]:
        rows = self._conn.execute(
            "SELECT collection, subcollection FROM saved_reels "
            "GROUP BY collection, subcollection ORDER BY collection, subcollection"
        ).fetchall()

        known: dict[str, list[str]] = {}
        for collection, subcollection in rows:
            subs = known.setdefault(collection, [])
            if subcollection and subcollection not in subs:
                subs.append(subcollection)
        return known

    def set_thumbnail_ref(self, normalized_url: str, thumbnail_ref: str) -> None:
        self._conn.execute(
            "UPDATE saved_reels SET thumbnail_ref = %s WHERE normalized_url = %s",
            (thumbnail_ref, normalized_url),
        )

    def find_by_author(self, name: str) -> list[SavedReel]:
        wanted = name.lstrip("@")
        rows = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels "
            "WHERE lower(author_handle) = lower(%s) OR lower(author_name) = lower(%s) "
            "ORDER BY saved_at DESC",
            (wanted, wanted),
        ).fetchall()
        return [_to_reel(row) for row in rows]

    def find_by_collection(self, collection: str) -> list[SavedReel]:
        rows = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels "
            "WHERE lower(collection) = lower(%s) ORDER BY saved_at DESC",
            (collection,),
        ).fetchall()
        return [_to_reel(row) for row in rows]

    def search(
        self, query_embedding: list[float], terms: list[str], top_k: int
    ) -> list[tuple[SavedReel, float]]:
        return merge_hits(
            self._vector_search(query_embedding, top_k),
            self._keyword_search(terms, top_k),
            top_k,
        )

    def _vector_search(
        self, query_embedding: list[float], top_k: int
    ) -> list[tuple[SavedReel, float]]:
        # `Vector` is required so the parameter is sent as pgvector's `vector`
        # type; a bare list adapts to `double precision[]`, which has no `<=>`
        # operator.
        vector = Vector(query_embedding)
        rows = self._conn.execute(
            f"SELECT {COLUMNS}, 1 - (embedding <=> %s) AS similarity "
            "FROM saved_reels ORDER BY embedding <=> %s LIMIT %s",
            (vector, vector, top_k),
        ).fetchall()
        return [(_to_reel(row[:-1]), float(row[-1])) for row in rows]

    def _keyword_search(
        self, terms: list[str], top_k: int
    ) -> list[tuple[SavedReel, float]]:
        """Reels whose curated metadata uses the query's words, scored by how
        much of the query each one accounts for.

        Two passes over the same terms: `to_tsquery` with them OR-ed together
        selects the candidate rows through the GIN index, then the correlated
        count says how many terms each candidate actually matched — which is
        what separates a reel tagged both "interviews" and "case prep" from
        one that merely mentions interviews. Terms are bare alphanumerics
        (`search_terms` guarantees it), so OR-ing them into a tsquery cannot
        smuggle in operators.
        """
        if not terms:
            return []
        rows = self._conn.execute(
            f"SELECT {COLUMNS}, ("
            "  SELECT count(*) FROM unnest(%s::text[]) AS t(term)"
            "   WHERE to_tsvector('english', metadata_text)"
            "         @@ plainto_tsquery('english', t.term)"
            ") AS matched "
            "FROM saved_reels "
            "WHERE to_tsvector('english', metadata_text) @@ to_tsquery('english', %s) "
            "ORDER BY matched DESC LIMIT %s",
            (terms, " | ".join(terms), top_k),
        ).fetchall()
        return [
            (_to_reel(row[:-1]), keyword_score(int(row[-1]), len(terms)))
            for row in rows
        ]


def _describe(dsn: str) -> str:
    """The host/port half of a DSN — never the credentials in front of it."""
    return dsn.rsplit("@", 1)[-1] if "@" in dsn else dsn


def _to_reel(row: tuple) -> SavedReel:
    (
        normalized_url,
        caption,
        tags,
        embedding,
        caption_embedding,
        collection,
        subcollection,
        author_handle,
        author_name,
        thumbnail_ref,
        user_placed,
        transcript_raw,
        transcript_summary,
        frame_analysis_raw,
        frame_analysis_summary,
        processing_status,
        saved_at,
    ) = row
    saved_at = saved_at if saved_at.tzinfo else saved_at.replace(tzinfo=timezone.utc)
    return SavedReel(
        url=normalized_url,
        caption=caption,
        tags=list(tags),
        embedding=_to_float_list(embedding),
        caption_embedding=(
            _to_float_list(caption_embedding) if caption_embedding is not None else []
        ),
        collection=collection,
        subcollection=subcollection,
        author_handle=author_handle,
        author_name=author_name,
        thumbnail_ref=thumbnail_ref,
        user_placed=user_placed,
        transcript_raw=transcript_raw or "",
        transcript_summary=transcript_summary or "",
        frame_analysis_raw=frame_analysis_raw or "",
        frame_analysis_summary=frame_analysis_summary or "",
        processing_status=_to_status(processing_status),
        saved_at=saved_at,
    )


def _to_status(value: str | None) -> ProcessingStatus:
    """A status the code does not recognize is read as SKIPPED rather than
    raising: an unknown value is a reel this build does not know how to
    process, and refusing to load the row at all would take down every query
    that happened to match it."""
    try:
        return ProcessingStatus(value)
    except ValueError:
        logger.warning("Unknown processing_status %r; treating as skipped", value)
        return ProcessingStatus.SKIPPED


def _to_float_list(embedding: Vector | Iterable[float]) -> list[float]:
    """`register_vector` hands back a pgvector `Vector`, which is not iterable."""
    if isinstance(embedding, Vector):
        return list(embedding.to_list())
    return [float(value) for value in embedding]
