"""Postgres/pgvector-backed `ReelStore`. One row per `SavedReel`."""

from __future__ import annotations

import logging
from collections.abc import Iterable
from datetime import timezone

import psycopg
from pgvector import Vector
from pgvector.psycopg import register_vector

from reel_vault.models import UNCATEGORIZED, SavedReel
from reel_vault.search import keyword_score, merge_hits, metadata_text

logger = logging.getLogger(__name__)

# Long enough for a container still waking up, short enough that a database
# that isn't there gets said out loud rather than waited on forever.
DEFAULT_CONNECT_TIMEOUT = 10

SCHEMA = f"""
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS saved_reels (
    normalized_url TEXT PRIMARY KEY,
    caption TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{{}}',
    embedding VECTOR(384) NOT NULL,
    saved_at TIMESTAMPTZ NOT NULL
);

-- Added after the first release; ALTERs keep existing vaults working.
ALTER TABLE saved_reels
    ADD COLUMN IF NOT EXISTS collection TEXT NOT NULL DEFAULT '{UNCATEGORIZED}',
    ADD COLUMN IF NOT EXISTS subcollection TEXT,
    ADD COLUMN IF NOT EXISTS author_handle TEXT,
    ADD COLUMN IF NOT EXISTS author_name TEXT,
    ADD COLUMN IF NOT EXISTS thumbnail_ref TEXT,
    -- The curated half of the reel, kept as plain text so the keyword arm of
    -- search has something to match. Written by `reel_vault.search`
    -- rather than generated by Postgres: `array_to_string` over `tags` is not
    -- immutable, so a GENERATED column is rejected outright, and duplicating
    -- the definition in SQL would let it drift from the one the in-memory
    -- store uses.
    ADD COLUMN IF NOT EXISTS metadata_text TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS saved_reels_collection_idx
    ON saved_reels (collection, subcollection);
CREATE INDEX IF NOT EXISTS saved_reels_author_idx ON saved_reels (author_handle);
-- An expression index, so the tsvector is built once per row at write time
-- rather than for every row on every search.
CREATE INDEX IF NOT EXISTS saved_reels_metadata_idx
    ON saved_reels USING GIN (to_tsvector('english', metadata_text));
"""

COLUMNS = (
    "normalized_url, caption, tags, embedding, collection, subcollection, "
    "author_handle, author_name, thumbnail_ref, saved_at"
)


class PostgresReelStore:
    def __init__(self, dsn: str, *, connect_timeout: int = DEFAULT_CONNECT_TIMEOUT) -> None:
        # Say where we are going before we try. An unreachable Postgres — the
        # container simply not started — TIMES OUT rather than refusing, so
        # without this the process hangs silently before the bot ever polls,
        # looking like a bot that starts fine and ignores every message.
        logger.info("Connecting to Postgres at %s", _describe(dsn))
        try:
            self._conn = psycopg.connect(
                dsn, autocommit=True, connect_timeout=connect_timeout
            )
        except psycopg.OperationalError as exc:
            raise RuntimeError(
                f"Could not reach Postgres at {_describe(dsn)} within "
                f"{connect_timeout}s. Is the database container running? "
                f"(psycopg: {exc})"
            ) from exc
        register_vector(self._conn)
        self._conn.execute(SCHEMA)
        logger.info("Connected to Postgres; vault ready.")

    def find_by_url(self, normalized_url: str) -> SavedReel | None:
        row = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels WHERE normalized_url = %s",
            (normalized_url,),
        ).fetchone()
        return _to_reel(row) if row else None

    def save(self, reel: SavedReel) -> bool:
        cursor = self._conn.execute(
            f"INSERT INTO saved_reels ({COLUMNS}, metadata_text) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (normalized_url) DO NOTHING",
            (
                reel.url,
                reel.caption,
                reel.tags,
                Vector(reel.embedding),
                reel.collection,
                reel.subcollection,
                reel.author_handle,
                reel.author_name,
                reel.thumbnail_ref,
                reel.saved_at,
                metadata_text(reel.tags, reel.collection, reel.subcollection),
            ),
        )
        # DO NOTHING leaves rowcount at 0 when the URL was already there.
        return cursor.rowcount > 0

    def update(self, reel: SavedReel) -> None:
        self._conn.execute(
            "UPDATE saved_reels SET collection = %s, subcollection = %s, "
            "embedding = %s, metadata_text = %s WHERE normalized_url = %s",
            (
                reel.collection,
                reel.subcollection,
                Vector(reel.embedding),
                metadata_text(reel.tags, reel.collection, reel.subcollection),
                reel.url,
            ),
        )

    def known_collections(self) -> dict[str, list[str]]:
        rows = self._conn.execute(
            "SELECT collection, subcollection FROM saved_reels "
            "GROUP BY collection, subcollection ORDER BY collection, subcollection"
        ).fetchall()

        known: dict[str, list[str]] = {}
        for collection, subcollection in rows:
            subs = known.setdefault(collection, [])
            if subcollection and subcollection not in subs:
                subs.append(subcollection)
        return known

    def set_thumbnail_ref(self, normalized_url: str, thumbnail_ref: str) -> None:
        self._conn.execute(
            "UPDATE saved_reels SET thumbnail_ref = %s WHERE normalized_url = %s",
            (thumbnail_ref, normalized_url),
        )

    def find_by_author(self, name: str) -> list[SavedReel]:
        wanted = name.lstrip("@")
        rows = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels "
            "WHERE lower(author_handle) = lower(%s) OR lower(author_name) = lower(%s) "
            "ORDER BY saved_at DESC",
            (wanted, wanted),
        ).fetchall()
        return [_to_reel(row) for row in rows]

    def find_by_collection(self, collection: str) -> list[SavedReel]:
        rows = self._conn.execute(
            f"SELECT {COLUMNS} FROM saved_reels "
            "WHERE lower(collection) = lower(%s) ORDER BY saved_at DESC",
            (collection,),
        ).fetchall()
        return [_to_reel(row) for row in rows]

    def search(
        self, query_embedding: list[float], terms: list[str], top_k: int
    ) -> list[tuple[SavedReel, float]]:
        return merge_hits(
            self._vector_search(query_embedding, top_k),
            self._keyword_search(terms, top_k),
            top_k,
        )

    def _vector_search(
        self, query_embedding: list[float], top_k: int
    ) -> list[tuple[SavedReel, float]]:
        # `Vector` is required so the parameter is sent as pgvector's `vector`
        # type; a bare list adapts to `double precision[]`, which has no `<=>`
        # operator.
        vector = Vector(query_embedding)
        rows = self._conn.execute(
            f"SELECT {COLUMNS}, 1 - (embedding <=> %s) AS similarity "
            "FROM saved_reels ORDER BY embedding <=> %s LIMIT %s",
            (vector, vector, top_k),
        ).fetchall()
        return [(_to_reel(row[:-1]), float(row[-1])) for row in rows]

    def _keyword_search(
        self, terms: list[str], top_k: int
    ) -> list[tuple[SavedReel, float]]:
        """Reels whose curated metadata uses the query's words, scored by how
        much of the query each one accounts for.

        Two passes over the same terms: `to_tsquery` with them OR-ed together
        selects the candidate rows through the GIN index, then the correlated
        count says how many terms each candidate actually matched — which is
        what separates a reel tagged both "interviews" and "case prep" from
        one that merely mentions interviews. Terms are bare alphanumerics
        (`search_terms` guarantees it), so OR-ing them into a tsquery cannot
        smuggle in operators.
        """
        if not terms:
            return []
        rows = self._conn.execute(
            f"SELECT {COLUMNS}, ("
            "  SELECT count(*) FROM unnest(%s::text[]) AS t(term)"
            "   WHERE to_tsvector('english', metadata_text)"
            "         @@ plainto_tsquery('english', t.term)"
            ") AS matched "
            "FROM saved_reels "
            "WHERE to_tsvector('english', metadata_text) @@ to_tsquery('english', %s) "
            "ORDER BY matched DESC LIMIT %s",
            (terms, " | ".join(terms), top_k),
        ).fetchall()
        return [
            (_to_reel(row[:-1]), keyword_score(int(row[-1]), len(terms)))
            for row in rows
        ]


def _describe(dsn: str) -> str:
    """The host/port half of a DSN — never the credentials in front of it."""
    return dsn.rsplit("@", 1)[-1] if "@" in dsn else dsn


def _to_reel(row: tuple) -> SavedReel:
    (
        normalized_url,
        caption,
        tags,
        embedding,
        collection,
        subcollection,
        author_handle,
        author_name,
        thumbnail_ref,
        saved_at,
    ) = row
    saved_at = saved_at if saved_at.tzinfo else saved_at.replace(tzinfo=timezone.utc)
    return SavedReel(
        url=normalized_url,
        caption=caption,
        tags=list(tags),
        embedding=_to_float_list(embedding),
        collection=collection,
        subcollection=subcollection,
        author_handle=author_handle,
        author_name=author_name,
        thumbnail_ref=thumbnail_ref,
        saved_at=saved_at,
    )


def _to_float_list(embedding: Vector | Iterable[float]) -> list[float]:
    """`register_vector` hands back a pgvector `Vector`, which is not iterable."""
    if isinstance(embedding, Vector):
        return list(embedding.to_list())
    return [float(value) for value in embedding]
